ExternalSecure: true
ExternalDomain: '0.0.0.0'
ExternalPort: 443

Database:
    postgres:
        Host: roundhouse.proxy.rlwy.net
        Port: 46997
        Database: zitadel
        MaxOpenConns: 25
        MaxConnLifetime: 1h
        MaxConnIdleTime: 5m
        Options:
        User:
            Username: zitadel
            Password: zitadel
            SSL:
                Mode: disable
                RootCert:
                Cert:
                Key:
        Admin:
            Username: postgres
            Password: F62beaD6E2F1A1cg3Gc3fAa1CD1f166c
            SSL:
                Mode: disable
                RootCert:
                Cert:
                Key: