FROM ghcr.io/zitadel/zitadel:latest

ARG ZITADEL_DATABASE_COCKROACH_HOST
ARG ZITADEL_EXTERNALSECURE
ENV ZITADEL_DATABASE_COCKROACH_HOST=${ZITADEL_DATABASE_COCKROACH_HOST}
ENV ZITADEL_EXTERNALSECURE=${ZITADEL_EXTERNALSECURE}

EXPOSE 8080

CMD ["start-from-init", "--masterkey", "MasterkeyNeedsToHave32Characters", "--tlsMode", "disabled"]
